config/routes.rb
Rails.application.routes.draw do
  get '/questions/myquestions', to: 'questions#myquestions', as: 'questions_myquestions'
  devise_for :users
  get 'welcome/index'
  resources :questions do
      resources :answers do
        member do
          put "upvote", to: "answers#upvote"
          put "downvote", to: "answers#downvote"
        end
      end
  end
  root 'welcome#index'
end

app/models/answer.rb
class Answer < ApplicationRecord
    belongs_to :question
    acts_as_votable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
    belongs_to :user
    has_many :answers, dependent: :destroy
    validates :question, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :questions
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
    def index
        @question = Question.find(params[:question_id])
        @answers = @question.answers.all
    end
    def new
        @question = Question.find(params[:question_id])
        @answer ||= Answer.new
    end
    def create
        @question = Question.find(params[:question_id])
        @answer = @question.answers.create(answer_params)
        redirect_to question_answers_path(@question)
    end
    def upvote
        @question = Question.find(params[:question_id])
        @answer = @question.answers.find(params[:id])
        @answer.upvote_by current_user
        redirect_to question_answers_path(@question)
    end
    def downvote
        @question = Question.find(params[:question_id])
        @answer = @question.answers.find(params[:id])
        @answer.downvote_by current_user
        redirect_to question_answers_path(@question)
    end
     
    private
        def answer_params
          params.require(:answer).permit(:answer, :answered_by)
        end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
    def index
        @questions = Question.all
    end

    def myquestions
        @questions = current_user.questions
    end

    def show
        @question = Question.find(params[:id])
    end

    def new
        @question ||= Question.new
    end

    def edit
        @question = Question.find(params[:id])
    end

    def create
        @question = current_user.questions.create(question_params)
        if @question.save
            flash[:notice] = "Success!"
            redirect_to @question
        else
            render "new"
        end
    end

    def update
        @question = Question.find(params[:id])
        if @question.update(question_params)
          redirect_to @question
        else
          render 'edit'
        end
    end

    
    def destroy
        @question = Question.find(params[:id])
        if @question.destroy
            flash[:notice] = "Deleted!"
            redirect_to questions_myquestions_path
        end
    end

    private
        def question_params
            params.require(:question).permit(:question)
        end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/answers/index.html.erb
<div style="margin-left: 60px;">
    <p>
    <h2><strong>Q.</strong>
    <%= @question.question %></h2>
    </p><br>
    <% @answers.each do |answer| %>
        <div style="border: 2px solid grey;border-radius:5px;padding-bottom:10px;width:600px">
            <h3 style="padding-left:15px;"><%= answer.answer %></h3>
            <strong style="padding-left:15px;">Answered by:</strong>
            <%= answer.answered_by %><br><br>
            <%= link_to 'Upvote', upvote_question_answer_path(answer.question_id, answer.id), method: :put, :style => "padding-left:15px;" %>
            <%= answer.get_upvotes.size %>
            <%= link_to 'Downvote', downvote_question_answer_path(answer.question_id, answer.id), method: :put %>
            <%= answer.get_downvotes.size %>
        </div><br>
    <% end %>

app/views/answers/new.html.erb
<div style="margin-left: 60px;">
    <p>
    <h2><strong>Q.</strong>
    <%= @question.question %></h2>
    </p>
    <h3>Add an answer:</h3>
    <%= form_with(model: [ @question, @question.answers.build ], local: true) do |form| %>
    <p>
        <%= form.text_area :answer, :style => "width:430px;height:80px;", :required => "required" %>
    </p>
    <p>
        <%= form.label :answered_by %><br>
        <%= form.text_field :answered_by, value: current_user.email, readonly: true %>
    </p>
    <p>
        <%= form.submit %>
    </p>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Askquo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <style>
       .navbar-custom{
          background-color: red;
        }
        .navbar-custom .navbar-brand, 
        .navbar-custom .navbar-text { 
            color: white; 
        }
        .nav.navbar-nav.navbar-right li a:hover {
          color: black;
        }
        .dropdown-menu a{
          color: black
        }
        .navbar-white a{
          color: white
        }
        .navbar-white a:hover{
          color: black
        }
        #navbarDropdown{
          color:white
        }
        #navbarDropdown:hover{
          color:black
        }
    </style>
  </head>
  <body>
    <nav class="navbar navbar-custom">
        <div class="container-fluid">
          <div class="navbar-brand">
            Askquo
          </div>
          <ul class="nav navbar-nav list">
              <li class="navbar-white"><%= link_to 'Home', welcome_index_path, :style => 'text-decoration:none;' %></li>
            <% if current_user %>
              <li class="navbar-white"><%= link_to 'Ask a Question', new_question_path, :style => 'text-decoration:none;' %></li>
              <li class="navbar-white"><%= link_to 'View all Questions', questions_path, :style => 'text-decoration:none;' %></li>
              <li class="navbar-white"><%= link_to 'My Questions', questions_myquestions_path, :style => 'text-decoration:none;' %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="glyphicon glyphicon-user"></span>&nbsp &nbsp<%= current_user.email %>
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown" style="width:220px;">
                <a class="dropdown-item"><%= link_to 'Change Password', edit_user_registration_path, :style => 'text-decoration:none;padding-left:35px;' %></a><br>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item"><%= link_to 'Log Out', destroy_user_session_path , method: :delete, :style => 'text-decoration:none;padding-left:35px;' %></a>
              </div>
            </li>
          </ul>
            <% else %>
              <li class="navbar-white"><%= link_to 'Sign Up', new_user_registration_path, :style => 'text-decoration:none;' %></li>
              <li class="navbar-white"><%= link_to 'Log In', new_user_session_path, :style => 'text-decoration:none;' %></li>
          </ul>
          <% end %>
        </div>
    </nav>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/questions/edit.html.erb
<%= render "devise/shared/error_messages", resource:  @question %>
<div style="margin-left: 60px;">
    <h2>Edit Question</h2>
    <br>
    <%= form_with(model: @question, local: true) do |form| %>
    <p>
        <%= form.label :enter_your_question %><br>
        <%= form.text_area :question, :required => 'required' %>
    </p>
    <p>
        <%= form.submit %>
    </p>
    <% end %>
</div>

app/views/questions/index.html.erb
<h2 style='padding-left:60px;'>Answer a question:</h2>
<br>
<div style='padding-left:60px; padding-right:60px'>
    <table class="table" style='padding-left:60px;'>
      <thead class="thead-dark">
        <tr>
            <th>Question:</th>
        </tr>
      </thead>
      <tbody>
        <% @questions.each do |question| %>
            <tr>
                <td><%= question.question %></td>
                <td><%= link_to 'View Answers', question_answers_path(question) %></td>
                <td><%= link_to 'Answer this question', new_question_answer_path(question) %></td>
            </tr>
        <% end %>
      </tbody>
    </table>
</div>

app/views/questions/myquestions.html.erb
<h2 style='padding-left:60px;'>My questions:</h2>
<br>
<div style='padding-left:60px; padding-right:60px'>
    <table class="table" style='padding-left:60px;'>
      <thead class="thead-dark">
        <tr>
            <th>Question:</th>
        </tr>
      </thead>
      <tbody>
        <% @questions.each do |question| %>
            <tr>
                <td><%= question.question %></td>
                <td><%= link_to 'View Answers', question_answers_path(question) %></td>
                <td><%= link_to 'Edit', edit_question_path(question) %></td>
                <td><%= link_to 'Delete', question_path(question),
                                                    method: :delete,
                                                    data: { confirm: 'Are you sure?' } %></td>
            </tr>
        <% end %>
      </tbody>
    </table>
</div>

app/views/questions/new.html.erb
<%= render "devise/shared/error_messages", resource:  @question %>
<div style="margin-left: 60px;">
    <h2>Ask Question</h2>
    <br>
    <%= form_with scope: :question, url: questions_path, local: true do |form| %>
    <p>
        <%= form.label :enter_your_question %><br>
        <%= form.text_area :question, :required => 'required', :style => "width:500px;height:60px" %>
    </p>
    <p>
        <%= form.submit %>
    </p>
    <% end %>
</div>

app/views/questions/show.html.erb
<div style="margin-left: 60px;">
    <h2>Following question has been raised:</h2>
    <br>
    <p>
        <strong>Q.</strong>
        <%= @question.question %>
    </p>
</div>

app/views/welcome/index.html.erb
<div class="jumbotron text-center">
  <h1>Askquo</h1>
  <p>Created by: Dewanshu Chhatlani</p> 
</div>

  
<div class="container">
  <div class="row">
    <div class="col-sm-4">
    </div>
    <div class="col-sm-4">
      <p>Asquo is a simple application which lets you ask questions and also lets you post answers to specific questions. A user can also edit or delete a question which he posted. Also there is an option to upvote/downvote a particular answer.</p>
    </div>
    <div class="col-sm-4">
    </div>
  </div>
</div>